### ISSUE TITLE
error when activating

### ISSUE THREAD

**Issue by larshp** [koemaeda/zdefuse#2]
Hi,
I get the following error when activating the code, looks like the table is not in git?

![image](https://user-images.githubusercontent.com/5888506/28744537-9313cf8c-7463-11e7-9245-f2474f82baa1.png)

**Comment by koemaeda** [comment]
That is a temporary table I created to list all the standard packages used in the unit tests. I have run the tests in a few customer systems that don't have the cross-reference tables properly filled for several of these packages. I had to run FOPC_DOCUMENTS_PROGCHECK for these packages for the unit tests to pass.

I forgot to comment it out before committing. Will fix that in the next commit.
For now you can just comment those lines out.

**Comment by koemaeda** [comment]
Just did a new commit, and this code is now commented out.
Later on I'll try to find a better way to keep track of these packages, maybe in a persistent static class (unit tests are run on different LUWs for complete separation).
