### ISSUE TITLE
ZCL_DEFUSE_OBJECT_CLAS test class not activated

### ISSUE THREAD

**Issue by larshp** [koemaeda/zdefuse#3]
The test class for ZCL_DEFUSE_OBJECT_CLAS is not added to the activation, due to missing `<WITH_UNIT_TESTS>X</WITH_UNIT_TESTS>` in the XML

**Comment by koemaeda** [comment]
ZCL_DEFUSE_OBJECT_CLAS doens't have a test class.
This class is just en empty extension of ZCL_DEFUSE_OBJECT_CLSD (the class definition object), which does have a test class.

**Comment by larshp** [comment]
okay, then file https://github.com/koemaeda/zdefuse/blob/master/src/zcl_defuse_object_clas.clas.testclasses.abap should be deleted
